name: Deploy MkDocs to GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.9.23
          cache: "pip"

      - name: Install MkDocs + plugins
        run: |
          pip install \
            mkdocs \
            mkdocs-material \
            mkdocstrings \
            mkdocstrings-python \
            mkdocs-gen-files \
            mkdocs-literate-nav \
            mkdocs-section-index \
            pymdown-extensions

      - name: Build documentation
        run: mkdocs build --clean --strict

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v4
        with:
          path: ./site

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4